ProyectoCloudPyme/Controllers/ArchivoController.cs
using ProyectoCloudPyme.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace ProyectoCloudPyme.Controllers
{
    public class ArchivoController : Controller
    {
        // GET: Archivo
  
        [HttpPost]
        public ActionResult Save(Archivo model)
        {
            string RutaSitio = Server.MapPath("~/");
            string PathAtchivo1 = Path.Combine(RutaSitio + "/Files/archivo1.png");
            string PathAtchivo2 = Path.Combine(RutaSitio + "/Files/archivo2.png");
            if (!ModelState.IsValid)
            {
               return RedirectToAction("SubirArchivos","Home",new { model });
            }
            model.archivo1.SaveAs(PathAtchivo1);
            model.archivo2.SaveAs(PathAtchivo2);
            @TempData["Message"] = "Se cargaron los archivos";
            return RedirectToAction("SubirArchivos","Home");

        }
    }
}

ProyectoCloudPyme/Controllers/HomeController.cs
using Microsoft.Ajax.Utilities;
using ProyectoCloudPyme.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Security;
using System.Web;
using System.Web.Mvc;
using static ProyectoCloudPyme.Models.Enum;

namespace ProyectoCloudPyme.Controllers
{
    public class HomeController : SweetController
    {
        Pagina mipagina = new Pagina();
        int cont = 0;
        public ActionResult SubirArchivos()
        {
            if (TempData["message"] != null)
            {
                ViewBag.Message = TempData["message"].ToString();
            }
            return View();
        }

        public ActionResult BienvenidaUsuario()
        {
            if (cont == 0)
            {
                cont = 1;
                mipagina.UsuarioAleatorio();
            }
            return View();  
        }

        public ActionResult InicioDeSesion() {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult Registrar()
        {
            return View();
        }
        public ActionResult EditarUsuario()
        {
            string email = (string)TempData["email"];
            TempData.Keep("email");
            string contraseña = (string)TempData["contraseña"];
            TempData.Keep("contraseña");

            Usuario usuario = mipagina.TraerUsuario(email, contraseña);

            return View(usuario);
        }

        public ActionResult GuiaPymeAlimentos()
        {
            return View();
        }

        public ActionResult GuiaPymeComercio()
        {
            return View();
        }

        public ActionResult GuiaPymeTransporte()
        {
            return View();
        }
        public ActionResult CapturarDatosPyme(){

            string email = (string)TempData["email"];
            TempData.Keep("email");
            string contraseña = (string)TempData["contraseña"];
            TempData.Keep("contraseña");

            Usuario usuario = mipagina.TraerUsuario(email, contraseña);

            string nombrePyme = Request.Form["nombrePyme"];
            string descripcion = Request.Form["Descripcion"];
            string tipoPyme = Request.Form["tipoPyme"];

            if (tipoPyme == "Comercio")
            {
                Comercio pymeComercio = new Comercio(nombrePyme,usuario, descripcion);
                usuario.Pymes.Add(pymeComercio);
            }
            else if (tipoPyme == "Transporte")
            {
                Transporte pymeTransporte = new Transporte(nombrePyme, usuario, descripcion);
                usuario.Pymes.Add(pymeTransporte);
            }
            else
            {
                Alimento pymeAlimento = new Alimento(nombrePyme,usuario,descripcion);
                usuario.Pymes.Add(pymeAlimento);
            }

            return RedirectToAction("SubirArchivos");
        }

        public ActionResult AccederSubirArchivos()
        {

            //También le puede pasar un usuario, atento
            return View("~/Views/Archivo/SubirArchivos.cshtml");
        }

        public ActionResult CrearPyme()
        {
            return View();
        }
        public ActionResult PaginaUsuario()
        {
            string email = (string)TempData["email"];
            TempData.Keep("email");
            string contraseña = (string)TempData["contraseña"];
            TempData.Keep("contraseña");

            Usuario usuario = mipagina.TraerUsuario(email, contraseña);
            return View(usuario);
        }
        public ActionResult VerificarExistencia()
        {
            
            string email = Request.Form["email"];
            string contraseña = Request.Form["contraseña"];

            if (mipagina.EstaRegistrado(email) && mipagina.ContraValida(contraseña))
            {
                TempData["email"] = email;
                TempData["contraseña"] = contraseña;
                TempData.Keep("email");
                TempData.Keep("contraseña");

                
                return RedirectToAction("PaginaUsuario");
                
            }

            Alert("No se encontró el usuario",NotificationType.error);
            //aqui va un alert
            return RedirectToAction("InicioDeSesion");
        }

        public ActionResult capturardatosRegistro() 
        {
            int id = Convert.ToInt32(Request.Form["id"]);
            string nombre = Request.Form["nombre"];
            string apellido_1 = Request.Form["apellido_1"];
            string apellido_2 = Request.Form["apellido_2"];
            DateTime fhnacimiento = DateTime.Parse(Request.Form["fh_nacimiento"]);
            string email = Request.Form["email"];
            string contraseña = Request.Form["contraseña"];

            Usuario usuario = new Usuario(id,nombre, apellido_1, apellido_2,fhnacimiento,email,contraseña);

            mipagina.AgregarUsuario(usuario);

            return RedirectToAction("InicioDeSesion");
        }

        public ActionResult ElegirPyme() 
        {
            return View();
        }

        public ActionResult CapturarDatosEdicion()
        {
            string nombre = Request.Form["nombre"];
            string apellido_1 = Request.Form["apellido_1"];
            string apellido_2 = Request.Form["apellido_2"];
            DateTime fhnacimiento = DateTime.Parse(Request.Form["fh_nacimiento"]);
            

            string email = (string)TempData["email"];
            TempData.Keep("email");
            string contraseña = (string)TempData["contraseña"];
            TempData.Keep("contraseña");

            Usuario usuario = mipagina.TraerUsuario(email, contraseña);

            usuario.Nombre = nombre;
            usuario.Apellido_1 = apellido_1;
            usuario.Apellido_2 = apellido_2;

            return RedirectToAction("VisualizarInformacion");

            
        }
        public ActionResult VisualizarInformacion()
        { 
            string email = (string)TempData["email"];
            TempData.Keep("email");
            string contraseña = (string)TempData["contraseña"];
            TempData.Keep("contraseña");

            Usuario usuario = mipagina.TraerUsuario(email, contraseña);

            return View(usuario);
        }


    }

}

ProyectoCloudPyme/Views/Home/BienvenidaUsuario.cshtml
@{
    ViewBag.Title = "Bienvenido";
    Layout = "";
}

<!DOCTYPE html>
<html>
<head>

    <title>Bienvenido</title>
    <link rel="stylesheet" href="~/Content/StyleView1.css" />

</head>
<body>
    <div class="container">
        <div class="left">
            <img src="http://drive.google.com/uc?export=view&id=12WOO71z5CBtqz7NXOS5IQI09bq1Mqf4d" style="width:475px; height:300px; margin-top:175px; margin-left:30px" />
        </div>
        <div class="right">
            <div>
                <h3>SOBRE NOSOTROS</h3>
                <h1>Bienvenido a CloudPyme</h1>
                <p>Este sitio le permitirá tener una guía para mejorar la administración de su negocio</p>
                <a href="@Url.Action("InicioDeSesion","Home")" id="comencemos">Comencemos</a>
            </div>
        </div>
    </div>

</body>
</html>

ProyectoCloudPyme/Views/Home/CrearPyme.cshtml
@{
    ViewBag.Title = "Creacion de Pyme";
    Layout = "~/Views/Shared/_LayoutCloudPymeSesion.cshtml";

}

<html>
<head>
    <title>Aquí te diremos los pasos para crear tu Pyme</title>
    <link rel="stylesheet" href="~/Content/StyleViewRegistro.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        .documentos {
            margin-top: 0;
            display: flex;
            background-size: cover;
            height: 80%;
            width: 100%;
            align-items: center;
            flex-direction: column;
            justify-content: space-between;
        }

        select {
            padding: 9px;
            border-radius: 0px;
            color: black;
            outline: none;
            border: none;
            border-bottom: solid 2px #0D4C43;
            background-color: #C7E6D7;
            width: 450px;
        }

            select:hover {
                border-color: #999;
            }

            select option {
                color: #333333;
                font-weight: bold;
                background-color: #b2caaa;
            }
    </style>
</head>

<body>

    <h1 style="margin-top:70px" >| Registro de nueva Pyme</h1>
    <div class="documentos" style="justify-content:center; align-items:center;">
        @using (Html.BeginForm("CapturarDatosPyme", "Home", FormMethod.Post))
        {
            <table style="border-collapse: separate; border-spacing: 20px;">
  
                <tr>
                    <td><i class="fa-sharp fa-solid fa-building" style="color: #0F5F54; font-size:25px"></i></td>
                    <td><input placeholder="Nombre de la Pyme" type="text" name="nombrePyme" pattern="[a-zA-Z.,:;()¿?¡!ñ ]+" autocomplete="off" required /></td>
                </tr>
                <tr>
                    <td style="color: #0F5F54; font-size:25px">&rArr;</td>
                    <td><input placeholder="Descripción" type="text" name="descripcion" pattern="[a-zA-Z.,:;()¿?¡!ñ ]+" autocomplete="off" required /></td>
                </tr>
                <tr>
                    <td style="color: #0F5F54; font-size:25px">&rArr;</td>
                    <td>
                        <select name="tipoPyme" id="afiliacion" style=" width: 300px;" required>
                            <option value="Comercio">Comercio</option>
                            <option value="Alimento">Alimento</option>
                            <option value="Transporte">Transporte</option>
                        </select>
                    </td>
                </tr>

            </table>
            <div style="text-align: center;">
                <input type="submit" value="Registrar Pyme">
            </div>
        }
    </div>
</body>
</html>

ProyectoCloudPyme/Views/Home/EditarUsuario.cshtml
@model ProyectoCloudPyme.Models.Usuario
@{
    ViewBag.Title = "EditarUsuario";
    Layout = "~/Views/Shared/_LayoutCloudPymeSesion.cshtml";

}
<html>
<head>
    <title>Editar Usuario</title>
    <link rel="stylesheet" href="~/Content/StyleViewRegistro.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
    </style>

</head>
<body style="margin-top:50px;">
    <div class="container" id="formulario">
        @using (Html.BeginForm("CapturarDatosEdicion", "Home", FormMethod.Post))
        {
            <h1>| Editar Información Usuario</h1>
            <table style="border-collapse: separate; border-spacing: 20px;">
                <tr>
                    <td><i class="fa-solid fa-person-walking" style="color: #0F5F54;"></i></td>
                    <td><input placeholder="Nombre" type="text" name="nombre" pattern="[a-zA-Z.,:;()¿?¡!ñ ]+" autocomplete="off" value="@Model.Nombre" required /></td>

                </tr>
                <tr>
                    <td style="color: #0F5F54; font-size:25px">&rArr;</td>
                    <td><input placeholder="Primer apellido" type="text" name="apellido_1" pattern="[a-zA-Z.,:;()¿?¡!ñ ]+" autocomplete="off" value="@Model.Apellido_1" /></td>
                </tr>
                <tr>
                    <td style="color: #0F5F54; font-size: 25px">&rArr;</td>
                    <td><input placeholder="Segundo apellido" type="text" name="apellido_2" pattern="[a-zA-Z.,:;()¿?¡!ñ ]+" autocomplete="off" value="@Model.Apellido_2"required /></td>
                </tr>
                <tr>
                    <td><i class="fa-solid fa-cake-candles" style="color: #0F5F54;"></i></td>
                    <td><input placeholder="" type="date" name="fh_nacimiento" value="@Model.Fhnacimiento" /></td>
                </tr>

            </table>
            <div style="text-align: center;">
                <input type="submit" value="Cambiar">
            </div>
        }
    </div>



</body>
</html>

ProyectoCloudPyme/Views/Home/ElegirPyme.cshtml
@{
    ViewBag.Title = "ElegirPyme";
    Layout = "~/Views/Shared/_LayoutCloudPymeSesion.cshtml";
}

<html>
<head>
    <title>Aquí te diremos los pasos para crear tu Pyme</title>
    <link rel="stylesheet" href="~/Content/StyleViewElegirPyme.css" />
    <style>

        .mia:hover {
            color: #F6F0E9;
            text-decoration: none;
            background-color: #3d8ac9;
        }

        #pymes {
            margin-top: 100px;
            display: flex;
            flex-direction:column;
            justify-content:center;
            flex-wrap:wrap;
            align-items:center;
            align-content:center;
            
        }
        .pyme-item {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

            .pyme-item a {
                margin-right: 10px;
            }
        .extra {
            font-size: 18px;
            color: #0F5F54;
            margin-right:5px;
        }
        .contenedorsin {
            display: flex;
            flex-direction: column;
            text-align: center;
            padding: 20px 35px;
            box-shadow: 0 5px 10px #333;
        }
    </style>
    
</head>

<body>

    <h4>Primero debes escoger el tipo de Pyme</h4>

    <div class="Pymes" id="pymes">
        <div class="contenedorsin">
            <div class="pyme-item">
                <span class="extra">&raquo;</span><a class="mia" href="@Url.Action("GuiaPymeAlimentos","Home")">Alimentos</a><span class="extra">&laquo;</span>
            </div>
            <div class="pyme-item">
                <span class="extra">&raquo;</span><a class="mia" href="@Url.Action("GuiaPymeTransporte","Home")">Transporte</a><span class="extra">&laquo;</span>
            </div>
            <div class="pyme-item">
                <span class="extra">&raquo;</span><a class="mia" href="@Url.Action("GuiaPymeComercio","Home")">Comercio</a><span class="extra">&laquo;</span>
            </div>
        </div>
    </div>


</body>
</html>

ProyectoCloudPyme/Views/Home/GuiaPymeAlimentos.cshtml
@{
    ViewBag.Title = "Alimentos ";
    Layout = "~/Views/Shared/_LayoutCloudPymeSesion.cshtml";
}
<html>
<head>
    <link rel="stylesheet" href="~/Content/StyleViewGuias.css" />
    <style>
    </style>
</head>
<body>
    <h1 id="titulo">Tramites para crear una <span>pyme</span> de Alimentos</h1>
    <div class="info">
        <h2><span>&bull;</span>Registro Único Tributario (RUT)</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                Es el primer paso para cualquier empresa en Colombia. El RUT tiene como objetivo identificar a los contribuyentes y facilitar el cumplimiento de sus
                obligaciones tributarias. Es necesario para realizar trámites relacionados con impuestos, presentar declaraciones, obtener licencias comerciales, realizar
                transacciones con entidades estatales y participar en actividades económicas en Colombia.
            </p>
            <p>
                El RUT está compuesto por un número de identificación único asignado a cada contribuyente.
                Para las personas naturales, generalmente corresponde al número de identificación personal (como el número de cédula de ciudadanía).
                Para las personas jurídicas, se asigna un número de identificación propio.
            </p>
        </div>
        <a href="https://www.tributi.com/blog/pasos-para-tramitar-el-rut-por-internet" target="_blank">Aquí tendrás la información necesaria para sacar tu RUT</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Registro Sanitario</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                Para asegurar la calidad e inocuidad de los alimentos que producirás y comercializarás, es necesario obtener el Registro Sanitario 
                ante el Instituto Nacional de Vigilancia de Medicamentos y Alimentos (INVIMA). El Registro Sanitario certifica que tu empresa cumple con los requisitos
                sanitarios establecidos para la producción y distribución de alimentos.

            </p>
        </div>
        <a href="https://www.invima.gov.co/tramite-para-registro-sanitario-de-alimentos-esto-es-lo-que-deben-saber" target="_blank">Aquí puedes obtener el registro</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Certificado manipulación de alimentos</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                El certificado de manipulación de alimentos es un documento que acredita que una persona ha recibido la formación y capacitación necesaria en higiene y manipulación de alimentos. 
                Este certificado es requerido en muchos países y jurisdicciones para aquellos que trabajan en
                la industria de alimentos y se encargan de la preparación, manipulación y servicio de alimentos.
            </p>
            <p>
                El objetivo del certificado de manipulación de alimentos es garantizar que las personas que trabajan en el sector alimentario tengan los conocimientos necesarios para garantizar
                la seguridad alimentaria y prevenir enfermedades transmitidas por alimentos. Al obtener este certificado, se demuestra que se han adquirido competencias en áreas como la higiene personal,
                manipulación adecuada de alimentos, control de temperaturas, almacenamiento seguro, limpieza y desinfección, entre otros aspectos relevantes.
            </p>
        </div>
        <a href="https://www.colcertificados.com/como-sacar-certificado-de-manipulacion-de-alimentos-en-colombia/" target="_blank">Aquí puedes obtener tu certificado</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Licencia de Funcionamiento</h2>
        <div class="parrafos" style="align-items:center">
            <p>Obtener la licencia de funcionamiento requerida por el municipio donde se ubique tu negocio, autorizando la apertura y operación de tu empresa.</p>
        </div>
        <a href="https://linkeatuabogado.com/cuales-son-los-pasos-para-obtener-la-licencia-de-funcionamiento/" target="_blank">Aquí puedes obtener tu licencia</a>
    </div>
</body>
</html>

ProyectoCloudPyme/Views/Home/GuiaPymeComercio.cshtml
@{
    ViewBag.Title = "Comercio";
    Layout = "~/Views/Shared/_LayoutCloudPymeSesion.cshtml";
}
<html>
<head>
    <link rel="stylesheet" href="~/Content/StyleViewGuias.css" />
    <style>

    </style>
</head>
<body>
    <h1 id="titulo">Tramites para crear una <span>pyme</span> de Comercio</h1>
    <div class="info">
        <h2><span>&bull;</span>Registro Único Tributario (RUT)</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                Es el primer paso para cualquier empresa en Colombia. El RUT tiene como objetivo identificar a los contribuyentes y facilitar el cumplimiento de sus
                obligaciones tributarias. Es necesario para realizar trámites relacionados con impuestos, presentar declaraciones, obtener licencias comerciales, realizar
                transacciones con entidades estatales y participar en actividades económicas en Colombia.
            </p>
            <p>
                El RUT está compuesto por un número de identificación único asignado a cada contribuyente.
                Para las personas naturales, generalmente corresponde al número de identificación personal (como el número de cédula de ciudadanía).
                Para las personas jurídicas, se asigna un número de identificación propio.
            </p>
        </div>
        <a href="https://www.tributi.com/blog/pasos-para-tramitar-el-rut-por-internet" target="_blank">Aquí tendrás la información necesaria para sacar tu RUT</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Registro Mercantil</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                Debes inscribir tu empresa en la Cámara de Comercio correspondiente a la ciudad donde se establecerá el negocio.
                El Registro Mercantil es un registro público donde se inscriben las empresas y comerciantes individuales para obtener su personería jurídica
                y cumplir con las obligaciones legales relacionadas con su actividad comercial.
                Su función principal es llevar un registro actualizado de la información de las empresas y garantizar la publicidad y transparencia de los actos
                y contratos mercantiles.
            </p>
            <p>
                El Registro Mercantil es administrado por las Cámaras de Comercio en Colombia. Al registrar una empresa en el Registro Mercantil,
                se le otorga la calidad de comerciante y se le asigna un Número de Identificación Tributaria (NIT),
                que es necesario para realizar trámites fiscales y comerciales.
            </p>
        </div>
        <a href="https://www.camaramedellin.com.co/servicios-registrales/mis-registros/registro-mercantil" target="_blank">Aquí tienes el link de la cámara de comercio</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Registro de Empleador</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                Si planeas contratar empleados, debes registrarte como empleador ante la Unidad de Registro de Aportes y Afiliaciones
                (U.R.A.A.) de la Administradora de Fondos de Pensiones (AFP) o ante la entidad administradora de Riesgos Laborales (ARL).
            </p>
        </div>
        <a href="https://www.mintrabajo.gov.co/atencion-al-ciudadano/transparencia/tramites-registrados-en-el-sistema-unico-de-informacion-de-tramites-suit" target="_blank">Aquí puedes obtener el registro</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Licencia de Funcionamiento</h2>
        <div class="parrafos" style="align-items:center">
            <p>Obtener la licencia de funcionamiento requerida por el municipio donde se ubique tu negocio, autorizando la apertura y operación de tu empresa.</p>
        </div>
        <a href="https://linkeatuabogado.com/cuales-son-los-pasos-para-obtener-la-licencia-de-funcionamiento/" target="_blank">Aquí puedes obtener tu licencia</a>
    </div>
</body>
</html>

ProyectoCloudPyme/Views/Home/GuiaPymeTransporte.cshtml
@{
    ViewBag.Title = "Transporte";
    Layout = "~/Views/Shared/_LayoutCloudPymeSesion.cshtml";
}
<html>
<head>
    <link rel="stylesheet" href="~/Content/StyleViewGuias.css" />
    <style>
    </style>
</head>
<body>
    <h1 id="titulo">Tramites para crear una <span>pyme</span> de Transporte</h1>
    <div class="info">
        <h2><span>&bull;</span>Registro Único Tributario (RUT)</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                Es el primer paso para cualquier empresa en Colombia. El RUT tiene como objetivo identificar a los contribuyentes y facilitar el cumplimiento de sus
                obligaciones tributarias. Es necesario para realizar trámites relacionados con impuestos, presentar declaraciones, obtener licencias comerciales, realizar
                transacciones con entidades estatales y participar en actividades económicas en Colombia.
            </p>
            <p>
                El RUT está compuesto por un número de identificación único asignado a cada contribuyente.
                Para las personas naturales, generalmente corresponde al número de identificación personal (como el número de cédula de ciudadanía).
                Para las personas jurídicas, se asigna un número de identificación propio.
            </p>
        </div>
        <a href="https://www.tributi.com/blog/pasos-para-tramitar-el-rut-por-internet" target="_blank">Aquí tendrás la información necesaria para sacar tu RUT</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Seguro Obligatorio de Accidentes de Tránsito (SOAT)</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                Adquiere el SOAT, que es un seguro obligatorio para los vehículos destinados al transporte de personas o mercancías en vías públicas.
            </p>
        </div>
        <a href="https://www.misoatvirtual.com.co/" target="_blank">Aquí puedes adquirir el SOAT</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Licencia de Transporte</h2>
        <div class="parrafos" style="align-items:center">
            <p>
                Para operar legalmente en el sector del transporte, debes obtener una licencia de transporte emitida por el Ministerio de Transporte de Colombia.
                Esta licencia puede variar según el tipo de transporte que desees realizar, como transporte de carga o transporte de pasajeros.
            </p>
        </div>
        <a href="https://www.mintransporte.gov.co/preguntas-frecuentes/98/transito--licencias-de-conduccion/" target="_blank">Aquí puedes obtener la licencia</a>
    </div>
    <hr />
    <div class="info">
        <h2><span>&bull;</span>Licencia de Funcionamiento</h2>
        <div class="parrafos" style="align-items:center">
            <p>Obtener la licencia de funcionamiento requerida por el municipio donde se ubique tu negocio, autorizando la apertura y operación de tu empresa.</p>
        </div>
        <a href="https://linkeatuabogado.com/cuales-son-los-pasos-para-obtener-la-licencia-de-funcionamiento/" target="_blank">Aquí puedes obtener tu licencia</a>
    </div>
</body>
</html>

ProyectoCloudPyme/Views/Home/MostrarLinkTransporte.cshtml
@{
    ViewBag.Title = "Link transporte";
    Layout = "~/Views/Shared/_LayoutPagina.cshtml";
}
<html>
<head>
    <link rel="stylesheet" href="~/Content/style.css" />
</head>
<body>
    <h3>Aquí puedes generar tu runt</h3>
    <table><tr><td><a href="https://www.runt.com.co/registros-runt/rnet-publico-privado" />Ingresa aquí</td></tr></table>

</body>
</html>

ProyectoCloudPyme/Views/Home/SubirArchivos.cshtml
@model ProyectoCloudPyme.Models.Archivo
@{
    ViewBag.Title = "Creacion de Pyme";
    Layout = "~/Views/Shared/_LayoutCloudPymeSesion.cshtml";

}

<html>
<head>
    <title>Carga de archivos</title>
    <link rel="stylesheet" href="~/Content/style.css" />

</head>

<body style="margin-top:15px">
    @if (ViewBag.Message != null)
    {
        <div class="alert-success" role="alert">
            @ViewBag.Message
        </div>
    }
    <h3 style="margin-top:40px; color:#191919">Debes subir los siguientes archivos</h3>
    <div class="documentos">
        @using (Html.BeginForm("Save", "Archivo", FormMethod.Post,
            new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col-md-6 col-lg-offset-3">
                    <div class="form-group">
                        @Html.LabelFor(d => d.archivo1)
                        @Html.TextBoxFor(d => d.archivo1, new { @class = "form-control", type = "file", accept = "" })
                        @Html.ValidationMessageFor(d => d.archivo1, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(d => d.archivo2)
                        @Html.TextBoxFor(d => d.archivo2, new { @class = "form-control", type = "file", accept = "" })
                        @Html.ValidationMessageFor(d => d.archivo2, "", new { @class = "text-danger" })
                    </div>
              
                    <div class="form-group" style="text-align:right">
                        <input type="submit" class="btn btn-success" value="Guardar">

                    </div>

                </div>
            </div>
        }
    </div>
</body>
</html>